version: '3.7'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.33.0
    ports:
      - 9090:9090
    volumes:
      - ./deploy/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager_sre
    ports:
      - '9093:9093'
  grafana:
    image: grafana/grafana-oss:8.3.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

  app:
    container_name: storage_api
    build:
      context: .
      dockerfile: ./src/docker/Dockerfile
    depends_on:
      - prometheus
    volumes:
      - ./src:/app
    ports:
      - "5000:5000"
   # command: make run
