{
 "title": "Python Storage API Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Avarage HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])/rate(http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "HTTP Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "response_status_code_total{}" }
   ]
  },
  {
   "title": "HTTP Response Status Code - Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(response_status_code_total[5m])"
    }
   ]
  }
 ]
}